# Generated by Django 5.2 on 2025-04-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_jobapplication_deadline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interviewing', 'Interviewing'), ('assesment', 'assesment'), ('rejected', 'Rejected'), ('offered', 'Offered'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='applied', max_length=20),
        ),
    ]
