# Generated by Django 5.2 on 2025-04-18 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_jobapplication_is_prepared_interviewprepdraft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewprepdraft",
            name="application",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_draft",
                to="applications.jobapplication",
            ),
        ),
    ]
