# Generated by Django 5.2 on 2025-04-19 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0009_coverletter_resume"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coverletter",
            name="content",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="content",
        ),
        migrations.AddField(
            model_name="coverletter",
            name="company",
            field=models.CharField(default="Unknown Company", max_length=255),
        ),
        migrations.AddField(
            model_name="coverletter",
            name="generated_content",
            field=models.TextField(default="To be generated"),
        ),
        migrations.AddField(
            model_name="coverletter",
            name="job_description",
            field=models.TextField(default="No description provided"),
        ),
        migrations.AddField(
            model_name="coverletter",
            name="job_title",
            field=models.CharField(default="Unknown Role", max_length=255),
        ),
        migrations.AddField(
            model_name="resume",
            name="generated_content",
            field=models.TextField(default="To be generated"),
        ),
        migrations.AddField(
            model_name="resume",
            name="job_description",
            field=models.TextField(default="No description provided"),
        ),
        migrations.AddField(
            model_name="resume",
            name="job_title",
            field=models.CharField(default="Unknown Role", max_length=255),
        ),
        migrations.AlterField(
            model_name="coverletter",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cover_letters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resumes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
