# Generated by Django 5.2 on 2025-04-20 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "applications",
            "0010_remove_coverletter_content_remove_resume_content_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("role_title", models.CharField(max_length=255)),
                (
                    "salary_range",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("top_reviews", models.JSONField(blank=True, null=True)),
                ("interview_questions", models.JSONField(blank=True, null=True)),
                ("experience_path", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
