# Generated by Django 5.2 on 2025-04-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0011_companyinsight"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinsight",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="companyinsight",
            name="source_links",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
