# Generated by Django 5.2 on 2025-04-21 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0012_companyinsight_location_companyinsight_source_links"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyinsight",
            name="location",
        ),
        migrations.RemoveField(
            model_name="companyinsight",
            name="source_links",
        ),
        migrations.AlterField(
            model_name="followupdraft",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="applications.jobapplication",
            ),
        ),
    ]
