# Generated by Django 5.2 on 2025-04-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0013_remove_companyinsight_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="followupdraft",
            name="email_follow_up_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="email_follow_up_sent",
            field=models.BooleanField(default=False),
        ),
    ]
