# Generated by Django 5.2 on 2025-04-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0014_followupdraft_email_follow_up_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="followupdraft",
            name="email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
