# Generated by Django 5.2 on 2025-04-21 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0016_interviewpracticesession_interviewquestionanswer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interviewpracticesession",
            options={"ordering": ["-started_at"]},
        ),
        migrations.AddField(
            model_name="interviewpracticesession",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="interviewpracticesession",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="interviewpracticesession",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_sessions",
                to="applications.jobapplication",
            ),
        ),
        migrations.AlterField(
            model_name="interviewpracticesession",
            name="interview_type",
            field=models.CharField(
                choices=[
                    ("phone", "Phone Interview"),
                    ("video", "Video Interview"),
                    ("formal", "Formal Interview"),
                    ("informal", "Informal Chat"),
                    ("technical", "Technical Interview"),
                    ("behavioral", "Behavioral Interview"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="interviewpracticesession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interview_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="InterviewMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("user", "Candidate"), ("ai", "Interviewer")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_question", models.BooleanField(default=False)),
                ("is_answer", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="applications.interviewpracticesession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("feedback_text", models.TextField()),
                ("strengths", models.TextField(blank=True)),
                ("areas_to_improve", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="applications.interviewmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="InterviewQuestionAnswer",
        ),
    ]
