# Generated by Django 5.2 on 2025-04-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0017_alter_interviewpracticesession_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewmessage",
            name="session",
        ),
        migrations.RemoveField(
            model_name="interviewpracticesession",
            name="application",
        ),
        migrations.RemoveField(
            model_name="interviewpracticesession",
            name="user",
        ),
        migrations.DeleteModel(
            name="InterviewFeedback",
        ),
        migrations.DeleteModel(
            name="InterviewMessage",
        ),
        migrations.DeleteModel(
            name="InterviewPracticeSession",
        ),
    ]
