# Generated by Django 5.2 on 2025-04-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0019_interviewsession_interviewmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="education",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="experience",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="skills",
            field=models.TextField(blank=True, null=True),
        ),
    ]
