# Generated by Django 5.2 on 2025-04-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0020_resume_education_resume_experience_resume_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="cover_letter_field",
            field=models.FileField(blank=True, null=True, upload_to="cover_letters/"),
        ),
    ]
