# Generated by Django 5.2 on 2025-04-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0021_jobapplication_cover_letter_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication",
            name="cover_letter_field",
        ),
    ]
