# Generated by Django 5.2 on 2025-04-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_secret',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
