# Generated by Django 5.2 on 2025-04-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_userprofile_otp_secret_userprofile_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='decoy_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
