# Generated by Django 5.2 on 2025-04-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='bill_receipts/'),
        ),
    ]
