# Generated by Django 5.2 on 2025-04-10 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='expiry_notified',
            field=models.BooleanField(default=False, help_text='Whether expiration notification has been sent'),
        ),
        migrations.AddField(
            model_name='document',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last expiration notification', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_size',
            field=models.PositiveIntegerField(help_text='Size in bytes'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['expiry_date'], name='documents_d_expiry__1d702a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_deleted'], name='documents_d_is_dele_490070_idx'),
        ),
    ]
