# Generated by Django 5.2 on 2025-04-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='category',
            field=models.CharField(choices=[('SOCIAL', 'Social Media'), ('EMAIL', 'Email Accounts'), ('FINANCE', 'Financial Services'), ('WORK', 'Work Related'), ('ENTERTAINMENT', 'Entertainment'), ('SHOPPING', 'Online Shopping'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
