# Generated by Django 5.2 on 2025-04-07 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Default')], default='system', max_length=10)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('enable_email_alerts', models.BooleanField(default=True)),
                ('default_job_app_view', models.CharField(choices=[('list', 'List View'), ('kanban', 'Kanban View'), ('calendar', 'Calendar View')], default='list', max_length=20)),
                ('encrypt_passwords', models.BooleanField(default=True)),
                ('auto_logout_minutes', models.IntegerField(default=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
